# Generated by Django 3.2 on 2022-04-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_gallery', '0016_change_verbose_names_and_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightgallery',
            name='pageThumbMarginHorizontal',
            field=models.CharField(default='0px', help_text='Horizontal margin of thumbnail on page', max_length=255, verbose_name='Page Thumb Horizontal Margin'),
        ),
        migrations.AddField(
            model_name='lightgallery',
            name='pageThumbMarginVertical',
            field=models.CharField(default='5px', help_text='Vertical margin of thumbnail on page', max_length=255, verbose_name='Page Thumb Vertical Margin'),
        ),
    ]
